/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.upf.ccc.appcontroleavaliacoes.view;

import br.upf.ccc.classes.Avaliacao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author catani
 */
public class TelaMain extends javax.swing.JPanel {
	
	List<Avaliacao> avaliacoes = new ArrayList<>();

	public TelaMain() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                tblAvaliacoes = new javax.swing.JTable();
                numberInputsPanel = new javax.swing.JPanel();
                txtFieldNotaUm = new javax.swing.JTextField();
                labelNotaUm = new javax.swing.JLabel();
                labelNotaDois = new javax.swing.JLabel();
                txtFieldNotaDois = new javax.swing.JTextField();
                labelNotaTres = new javax.swing.JLabel();
                txtFieldNotaTres = new javax.swing.JTextField();
                labelNotaRec = new javax.swing.JLabel();
                txtFieldNotaRec = new javax.swing.JTextField();
                labelNotaExame = new javax.swing.JLabel();
                txtFieldNotaExame = new javax.swing.JTextField();
                footerBar = new javax.swing.JPanel();
                labelStatus = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                btnAlterar = new javax.swing.JButton();
                btnListar = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                btnExcluir = new javax.swing.JButton();
                btnInserir = new javax.swing.JButton();
                inputsPanel = new javax.swing.JPanel();
                labelNome = new javax.swing.JLabel();
                txtNome = new javax.swing.JTextField();
                labelMatr = new javax.swing.JLabel();
                txtMatricula = new javax.swing.JTextField();
                btnCopiarLinha = new javax.swing.JButton();

                tblAvaliacoes.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null}
                        },
                        new String [] {
                                "Matrícula", "Nome", "Nota Um", "Nota Dois", "Nota Três", "Recuperação", "Exame", "Média", "Situação"
                        }
                ));
                jScrollPane1.setViewportView(tblAvaliacoes);

                txtFieldNotaUm.setPreferredSize(new java.awt.Dimension(40, 25));

                labelNotaUm.setText("Nota Um");

                labelNotaDois.setText("Nota Dois");

                txtFieldNotaDois.setPreferredSize(new java.awt.Dimension(40, 25));

                labelNotaTres.setText("Nota Três");

                txtFieldNotaTres.setPreferredSize(new java.awt.Dimension(40, 25));
                txtFieldNotaTres.addActionListener(this::txtFieldNotaTresActionPerformed);

                labelNotaRec.setText("Nota Recuperação");

                txtFieldNotaRec.setPreferredSize(new java.awt.Dimension(40, 25));

                labelNotaExame.setText("Nota Exame");

                txtFieldNotaExame.setPreferredSize(new java.awt.Dimension(40, 25));

                javax.swing.GroupLayout numberInputsPanelLayout = new javax.swing.GroupLayout(numberInputsPanel);
                numberInputsPanel.setLayout(numberInputsPanelLayout);
                numberInputsPanelLayout.setHorizontalGroup(
                        numberInputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(numberInputsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(numberInputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelNotaUm)
                                        .addComponent(labelNotaDois)
                                        .addComponent(labelNotaTres)
                                        .addComponent(labelNotaRec)
                                        .addComponent(labelNotaExame))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(numberInputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(numberInputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtFieldNotaRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFieldNotaTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFieldNotaExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numberInputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtFieldNotaUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFieldNotaDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );
                numberInputsPanelLayout.setVerticalGroup(
                        numberInputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(numberInputsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(numberInputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(numberInputsPanelLayout.createSequentialGroup()
                                                .addGroup(numberInputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtFieldNotaUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(labelNotaUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFieldNotaDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFieldNotaTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(numberInputsPanelLayout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(labelNotaDois, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelNotaTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(numberInputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelNotaRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFieldNotaRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(numberInputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtFieldNotaExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelNotaExame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

                javax.swing.GroupLayout footerBarLayout = new javax.swing.GroupLayout(footerBar);
                footerBar.setLayout(footerBarLayout);
                footerBarLayout.setHorizontalGroup(
                        footerBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerBarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                footerBarLayout.setVerticalGroup(
                        footerBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                );

                jPanel1.setPreferredSize(new java.awt.Dimension(150, 120));

                btnAlterar.setText("Alterar");
                btnAlterar.addActionListener(this::btnAlterarActionPerformed);

                btnListar.setText("Listar");
                btnListar.addActionListener(this::btnListarActionPerformed);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
                );

                jPanel2.setPreferredSize(new java.awt.Dimension(150, 120));

                btnExcluir.setText("Excluir");
                btnExcluir.addActionListener(this::btnExcluirActionPerformed);

                btnInserir.setText("Inserir");
                btnInserir.setPreferredSize(new java.awt.Dimension(70, 23));
                btnInserir.addActionListener(this::btnInserirActionPerformed);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                );

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                labelNome.setText("Nome:");

                txtNome.setMinimumSize(new java.awt.Dimension(64, 30));

                labelMatr.setText("Matrícula:");

                txtMatricula.setPreferredSize(new java.awt.Dimension(64, 30));

                btnCopiarLinha.setText("Copiar Linha Selecionada");
                btnCopiarLinha.addActionListener(this::btnCopiarLinhaActionPerformed);

                javax.swing.GroupLayout inputsPanelLayout = new javax.swing.GroupLayout(inputsPanel);
                inputsPanel.setLayout(inputsPanelLayout);
                inputsPanelLayout.setHorizontalGroup(
                        inputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(inputsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(inputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelMatr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCopiarLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                inputsPanelLayout.setVerticalGroup(
                        inputsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(inputsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelMatr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(btnCopiarLinha)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1)
                                                .addGap(6, 6, 6))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(inputsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(numberInputsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
                        .addComponent(footerBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numberInputsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(footerBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void txtFieldNotaTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNotaTresActionPerformed
        }//GEN-LAST:event_txtFieldNotaTresActionPerformed

        private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
		Integer index = tblAvaliacoes.getSelectedRow();
		try { 
			excluirAvaliacaoAtIndex(index); 
			labelStatus.setText("Avaliação excluída com sucesso!");
		}
		catch (Exception ex) { labelStatus.setText(ex.getMessage()); }
		listarAvaliacoes(avaliacoes);
        }//GEN-LAST:event_btnExcluirActionPerformed

        private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
		inserirOuAlterar(null);
	}
	private void inserirOuAlterar(Integer index) {
		String nome;
		Integer matricula;
		String input;
		Float notaUm;
		Float notaDois;
		Float notaTres;
		Float notaRec;
		Float notaExame;
		try {
			input = txtNome.getText();
			nome = input.isEmpty() ? null : input;
			input = txtMatricula.getText();
			matricula = input.isEmpty() ? null : Integer.valueOf(input);
			input = txtFieldNotaUm.getText();
			notaUm = input.isEmpty() ? null : Float.valueOf(input);
			input = txtFieldNotaDois.getText();
			notaDois = input.isEmpty() ? null : Float.valueOf(input);
			input = txtFieldNotaTres.getText();
			notaTres = input.isEmpty() ? null : Float.valueOf(input);
			input = txtFieldNotaRec.getText();
			System.out.println("input: " + input);
			System.out.println("Is empty? " + input.isEmpty());
			notaRec = input.isEmpty() ? null : Float.valueOf(input);
			input = txtFieldNotaExame.getText();
			notaExame = input.isEmpty() ? null : Float.valueOf(input);

			try {
				Avaliacao a;
				a = new Avaliacao(matricula, nome, notaUm, notaDois, notaTres, notaRec, notaExame);
				if (index != null) {
					excluirAvaliacaoAtIndex(index);
					avaliacoes.add(index, a);
					labelStatus.setText("Avaliação alterada com sucesso!");
				} else {
					avaliacoes.add(a);
					labelStatus.setText("Avaliação inserida com sucesso!");
				}
				
				listarAvaliacoes(avaliacoes);
				limparFields();

			} catch (Exception ex) { // erro na inicialização
				System.err.println(ex);
				labelStatus.setText("Não foi possível inserir! " + ex.getMessage());
			}
		} catch (NumberFormatException ex) {
			labelStatus.setText("Não foi possível inserir! " + "As notas devem ser numéricas!");
		}
        }//GEN-LAST:event_btnInserirActionPerformed

        private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
//		avaliacoes = dao.getLista(); 
		listarAvaliacoes(avaliacoes);
	}
	private void listarAvaliacoes(List<Avaliacao> lista) {
		DefaultTableModel dtm = (DefaultTableModel) tblAvaliacoes.getModel(); 
		dtm.setRowCount(0); 
		for(Avaliacao a : lista){ 
			Float media = null;
			String situacao = null;
			try {
				media = a.getMediaFinal();
				situacao = a.getSituacao();
			} catch (Exception ex) {
				labelStatus.setText(ex.getMessage());
			}
			dtm.addRow(new Object[] {
				a.getMatricula(),
				a.getNome(),
				a.getNotaUm(),
				a.getNotaDois(),
				a.getNotaTres(),
				a.getNotaRecuperacao(),
				a.getNotaExame(),
				media,
				situacao
			});
       }

                // TODO add your handling code here:
        }//GEN-LAST:event_btnListarActionPerformed

        private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
		int index = tblAvaliacoes.getSelectedRow();

		inserirOuAlterar(index);
		
                // TODO add your handling code here:
        }//GEN-LAST:event_btnAlterarActionPerformed

        private void btnCopiarLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarLinhaActionPerformed
		Integer index = tblAvaliacoes.getSelectedRow();
		if (index != -1) preencherFields(index);
        }//GEN-LAST:event_btnCopiarLinhaActionPerformed

	private void excluirAvaliacaoAtIndex(int index) throws Exception {
		try { avaliacoes.remove(index); }
		catch (Exception ex) {throw new Exception("Não foi possível excluir!"); }
	}

	private void limparFields() {
        	txtFieldNotaDois.setText("");
        	txtFieldNotaExame.setText("");
        	txtFieldNotaRec.setText("");
        	txtFieldNotaTres.setText("");
        	txtFieldNotaUm.setText("");
        	txtMatricula.setText("");
        	txtNome.setText("");
	}

	private void preencherFields(int index) {
		Avaliacao a = avaliacoes.get(index);
        	txtMatricula.setText(String.valueOf(a.getMatricula()));
        	txtNome.setText(a.getNome());
        	txtFieldNotaUm.setText(String.valueOf(a.getNotaUm()));
		if ("null".equals(txtFieldNotaUm.getText())) txtFieldNotaUm.setText("");
        	txtFieldNotaDois.setText(String.valueOf(a.getNotaDois()));
		if ("null".equals(txtFieldNotaDois.getText())) txtFieldNotaDois.setText("");
        	txtFieldNotaTres.setText(String.valueOf(a.getNotaTres()));
		if ("null".equals(txtFieldNotaTres.getText())) txtFieldNotaTres.setText("");
        	txtFieldNotaRec.setText(String.valueOf(a.getNotaRecuperacao()));
		if ("null".equals(txtFieldNotaRec.getText())) txtFieldNotaRec.setText("");
        	txtFieldNotaExame.setText(String.valueOf(a.getNotaExame()));
		if ("null".equals(txtFieldNotaExame.getText())) txtFieldNotaExame.setText("");
	}
	
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAlterar;
        private javax.swing.JButton btnCopiarLinha;
        private javax.swing.JButton btnExcluir;
        private javax.swing.JButton btnInserir;
        private javax.swing.JButton btnListar;
        private javax.swing.JPanel footerBar;
        private javax.swing.JPanel inputsPanel;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel labelMatr;
        private javax.swing.JLabel labelNome;
        private javax.swing.JLabel labelNotaDois;
        private javax.swing.JLabel labelNotaExame;
        private javax.swing.JLabel labelNotaRec;
        private javax.swing.JLabel labelNotaTres;
        private javax.swing.JLabel labelNotaUm;
        private javax.swing.JLabel labelStatus;
        private javax.swing.JPanel numberInputsPanel;
        private javax.swing.JTable tblAvaliacoes;
        private javax.swing.JTextField txtFieldNotaDois;
        private javax.swing.JTextField txtFieldNotaExame;
        private javax.swing.JTextField txtFieldNotaRec;
        private javax.swing.JTextField txtFieldNotaTres;
        private javax.swing.JTextField txtFieldNotaUm;
        private javax.swing.JTextField txtMatricula;
        private javax.swing.JTextField txtNome;
        // End of variables declaration//GEN-END:variables
}